import { NextResponse } from "next/server";

import type { Appointment, DentalRecord, Invoice, PatientProfile } from "@/lib/clinic-types";
import { getDatabase } from "@/lib/mongodb";
import {
  buildPatientAnalytics,
  buildPatientDuplicateCandidates,
  generatePatientId,
  normalizePatientForStorage,
  serializePatient,
  type PatientDocument,
} from "@/lib/patients";

function escapeRegex(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function errorResponse(message: string, error: unknown) {
  return NextResponse.json(
    {
      error: message,
      details:
        process.env.NODE_ENV === "development"
          ? error instanceof Error
            ? error.message
            : String(error)
          : undefined,
    },
    { status: 500 },
  );
}

export async function GET(request: Request) {
  try {
    const db = await getDatabase();
    const { searchParams } = new URL(request.url);
    const q = searchParams.get("q")?.trim() ?? "";
    const patientQuery = q
      ? {
          $or: [
            { patientId: { $regex: escapeRegex(q), $options: "i" } },
            { nationalId: { $regex: escapeRegex(q), $options: "i" } },
            { passportNumber: { $regex: escapeRegex(q), $options: "i" } },
            { fullName: { $regex: escapeRegex(q), $options: "i" } },
            { phone: { $regex: escapeRegex(q), $options: "i" } },
            { phoneNumbers: { $elemMatch: { $regex: escapeRegex(q), $options: "i" } } },
            { email: { $regex: escapeRegex(q), $options: "i" } },
          ],
        }
      : {};

    const [patients, appointments, invoices, records] = await Promise.all([
      db.collection<PatientDocument>("patients").find(patientQuery).sort({ _id: -1 }).toArray(),
      db.collection<Omit<Appointment, "id"> & { _id?: unknown }>("appointments").find({}).toArray(),
      db.collection<Omit<Invoice, "id"> & { _id?: unknown }>("billing_invoices").find({}).toArray(),
      db.collection<Omit<DentalRecord, "id"> & { _id?: unknown }>("emr_records").find({}).toArray(),
    ]);

    const serializedAppointments = appointments.map((appointment) => ({
      id: String(appointment._id),
      patientId: appointment.patientId,
      patientName: appointment.patientName,
      dentist: appointment.dentist,
      date: appointment.date,
      time: appointment.time,
      reason: appointment.reason,
      status: appointment.status,
      reminderDate: appointment.reminderDate,
      reminderChannel: appointment.reminderChannel,
      followUpDate: appointment.followUpDate,
      notes: appointment.notes,
    }));
    const serializedInvoices = invoices.map((invoice) => ({
      id: String(invoice._id),
      patientId: invoice.patientId,
      patientName: invoice.patientName,
      invoiceNumber: invoice.invoiceNumber,
      issueDate: invoice.issueDate,
      linkedRecordId: invoice.linkedRecordId ?? "",
      autoGenerated: invoice.autoGenerated ?? false,
      lineItems: invoice.lineItems ?? [],
      payments: invoice.payments ?? [],
      notes: invoice.notes ?? "",
    }));
    const serializedRecords = records.map((record) => ({
      id: String(record._id),
      patientId: record.patientId,
      patientName: record.patientName,
      visitDate: record.visitDate,
      chiefComplaint: record.chiefComplaint,
      consultationNotes: record.consultationNotes,
      diagnoses: record.diagnoses,
      treatmentPlan: record.treatmentPlan,
      treatmentStep: record.treatmentStep ?? "",
      treatmentStatus: record.treatmentStatus ?? "planned",
      procedureHistory: record.procedureHistory,
      clinicalAttachments: record.clinicalAttachments ?? [],
      odontogram: record.odontogram ?? [],
    }));
    const normalizedPatients = patients.map((patient) =>
      serializePatient(patient, {
        analytics: buildPatientAnalytics(
          String(patient._id),
          serializedAppointments,
          serializedInvoices,
          serializedRecords,
        ),
        appointments: serializedAppointments.filter(
          (appointment) => appointment.patientId === String(patient._id),
        ),
        invoices: serializedInvoices.filter((invoice) => invoice.patientId === String(patient._id)),
      }),
    );

    return NextResponse.json(
      normalizedPatients.map((patient) => ({
        ...patient,
        duplicateCandidates: buildPatientDuplicateCandidates(patient, normalizedPatients),
      })) satisfies PatientProfile[],
    );
  } catch (error) {
    console.error("GET /api/patients failed", error);
    return errorResponse("Failed to load patients from MongoDB.", error);
  }
}

export async function POST(request: Request) {
  try {
    const payload = (await request.json()) as Partial<PatientProfile>;
    const db = await getDatabase();
    const patientId = payload.patientId?.trim() || (await generatePatientId(db));
    const nextPatient = normalizePatientForStorage({
      ...payload,
      patientId,
      registrationDate: payload.registrationDate || new Date().toISOString(),
    });
    const result = await db.collection<PatientDocument>("patients").insertOne(nextPatient);

    return NextResponse.json(
      serializePatient({ _id: result.insertedId, ...nextPatient }),
      { status: 201 },
    );
  } catch (error) {
    console.error("POST /api/patients failed", error);
    return errorResponse("Failed to save patient to MongoDB.", error);
  }
}
