import { ObjectId } from "mongodb";
import { NextResponse } from "next/server";

import type { Appointment, DentalRecord, Invoice, PatientProfile } from "@/lib/clinic-types";
import { getDatabase } from "@/lib/mongodb";
import {
  buildPatientAnalytics,
  buildPatientDuplicateCandidates,
  buildPatientFamilyMembers,
  normalizePatientForStorage,
  serializePatient,
  type PatientDocument,
  type PatientNoteDocument,
} from "@/lib/patients";

function errorResponse(message: string, error: unknown) {
  return NextResponse.json(
    {
      error: message,
      details:
        process.env.NODE_ENV === "development"
          ? error instanceof Error
            ? error.message
            : String(error)
          : undefined,
    },
    { status: 500 },
  );
}

export async function GET(
  _request: Request,
  context: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await context.params;
    const db = await getDatabase();
    const [patient, allPatients, appointments, invoices, records, notes] = await Promise.all([
      db.collection<PatientDocument>("patients").findOne({ _id: new ObjectId(id) }),
      db.collection<PatientDocument>("patients").find({}).toArray(),
      db.collection<Omit<Appointment, "id"> & { _id?: unknown }>("appointments")
        .find({ patientId: id })
        .toArray(),
      db.collection<Omit<Invoice, "id"> & { _id?: unknown }>("billing_invoices")
        .find({ patientId: id })
        .toArray(),
      db.collection<Omit<DentalRecord, "id"> & { _id?: unknown }>("emr_records")
        .find({ patientId: id })
        .toArray(),
      db.collection<PatientNoteDocument>("patientNotes")
        .find({ patientId: id })
        .sort({ createdAt: -1, _id: -1 })
        .toArray(),
    ]);

    if (!patient) {
      return NextResponse.json({ error: "Patient not found." }, { status: 404 });
    }

    const serializedAppointments = appointments.map((appointment) => ({
      id: String(appointment._id),
      patientId: appointment.patientId,
      patientName: appointment.patientName,
      dentist: appointment.dentist,
      date: appointment.date,
      time: appointment.time,
      reason: appointment.reason,
      status: appointment.status,
      reminderDate: appointment.reminderDate,
      reminderChannel: appointment.reminderChannel,
      followUpDate: appointment.followUpDate,
      notes: appointment.notes,
    }));
    const serializedInvoices = invoices.map((invoice) => ({
      id: String(invoice._id),
      patientId: invoice.patientId,
      patientName: invoice.patientName,
      invoiceNumber: invoice.invoiceNumber,
      issueDate: invoice.issueDate,
      linkedRecordId: invoice.linkedRecordId ?? "",
      autoGenerated: invoice.autoGenerated ?? false,
      lineItems: invoice.lineItems ?? [],
      payments: invoice.payments ?? [],
      notes: invoice.notes ?? "",
    }));
    const serializedRecords = records.map((record) => ({
      id: String(record._id),
      patientId: record.patientId,
      patientName: record.patientName,
      visitDate: record.visitDate,
      chiefComplaint: record.chiefComplaint,
      consultationNotes: record.consultationNotes,
      diagnoses: record.diagnoses,
      treatmentPlan: record.treatmentPlan,
      treatmentStep: record.treatmentStep ?? "",
      treatmentStatus: record.treatmentStatus ?? "planned",
      procedureHistory: record.procedureHistory,
      clinicalAttachments: record.clinicalAttachments ?? [],
      odontogram: record.odontogram ?? [],
    }));
    const normalizedAllPatients = allPatients.map((item) =>
      serializePatient(item, { notesTimeline: [] }),
    );
    const response = serializePatient(patient, {
      analytics: buildPatientAnalytics(id, serializedAppointments, serializedInvoices, serializedRecords),
      notesTimeline: notes.map((note) => ({
        id: String(note._id),
        patientId: note.patientId,
        createdAt: note.createdAt,
        staffUser: note.staffUser,
        noteType: note.noteType,
        content: note.content,
      })),
      duplicateCandidates: buildPatientDuplicateCandidates(
        { id, ...normalizePatientForStorage(patient) },
        normalizedAllPatients,
      ),
      familyMembers: buildPatientFamilyMembers(
        { id, ...normalizePatientForStorage(patient) },
        normalizedAllPatients,
      ),
      appointments: serializedAppointments,
      invoices: serializedInvoices,
    });

    return NextResponse.json(response);
  } catch (error) {
    console.error("GET /api/patients/[id] failed", error);
    return errorResponse("Failed to load patient profile.", error);
  }
}

export async function PATCH(
  request: Request,
  context: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await context.params;
    const payload = (await request.json()) as Partial<PatientProfile>;
    const db = await getDatabase();
    const patients = db.collection<PatientDocument>("patients");
    const existing = await patients.findOne({ _id: new ObjectId(id) });

    if (!existing) {
      return NextResponse.json({ error: "Patient not found." }, { status: 404 });
    }

    const nextPatient = normalizePatientForStorage(payload, existing);
    await patients.updateOne({ _id: new ObjectId(id) }, { $set: nextPatient });

    return NextResponse.json(serializePatient({ _id: new ObjectId(id), ...nextPatient }));
  } catch (error) {
    console.error("PATCH /api/patients/[id] failed", error);
    return errorResponse("Failed to update patient profile.", error);
  }
}

export async function DELETE(
  _request: Request,
  context: { params: Promise<{ id: string }> },
) {
  try {
    const { id } = await context.params;
    const db = await getDatabase();

    await Promise.all([
      db.collection("patients").deleteOne({ _id: new ObjectId(id) }),
      db.collection("patientNotes").deleteMany({ patientId: id }),
    ]);

    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error("DELETE /api/patients/[id] failed", error);
    return errorResponse("Failed to delete patient profile.", error);
  }
}
