import oracledb from "oracledb";
import { NextResponse } from "next/server";

import type { Invoice, PaymentRecord } from "@/lib/clinic-types";
import { withOracleConnection } from "@/lib/oracle";

type InvoiceRow = {
  ID: number;
  PATIENT_ID: number | null;
  TOTAL_AMOUNT: number;
  NOTES: string | null;
  CREATED_AT: Date | string | null;
};

type InvoiceMetadata = Omit<Invoice, "id"> & {
  status?: string;
};

function parseJson<T>(value: string | null, fallback: T): T {
  if (!value) {
    return fallback;
  }

  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}

function sumPayments(payments: PaymentRecord[]) {
  return payments.reduce((total, payment) => total + payment.amount, 0);
}

function formatIsoDate(value: Date | string | null) {
  if (!value) {
    return new Date().toISOString().slice(0, 10);
  }

  if (typeof value === "string") {
    return value;
  }

  return value.toISOString();
}

function serializeInvoice(row: InvoiceRow): Invoice {
  const metadata = parseJson<InvoiceMetadata>(row.NOTES, {
    patientId: row.PATIENT_ID ? String(row.PATIENT_ID) : "",
    patientName: "",
    invoiceNumber: "",
    issueDate: formatIsoDate(row.CREATED_AT),
    linkedRecordId: "",
    autoGenerated: false,
    lineItems: [],
    payments: [],
    notes: "",
  });

  return {
    id: String(row.ID),
    patientId: metadata.patientId,
    patientName: metadata.patientName,
    invoiceNumber: metadata.invoiceNumber,
    issueDate: metadata.issueDate,
    linkedRecordId: metadata.linkedRecordId ?? "",
    autoGenerated: metadata.autoGenerated ?? false,
    lineItems: metadata.lineItems ?? [],
    payments: metadata.payments ?? [],
    notes: metadata.notes ?? "",
  };
}

function buildInvoiceMetadata(payload: Omit<Invoice, "id">) {
  return JSON.stringify({
    patientId: payload.patientId,
    patientName: payload.patientName,
    invoiceNumber: payload.invoiceNumber,
    issueDate: payload.issueDate,
    linkedRecordId: payload.linkedRecordId,
    autoGenerated: payload.autoGenerated,
    lineItems: payload.lineItems,
    payments: payload.payments,
    notes: payload.notes,
    status: sumPayments(payload.payments) >= payload.lineItems.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0)
      ? "paid"
      : "pending",
  } satisfies InvoiceMetadata);
}

function parseNumericPatientId(patientId: string) {
  const parsed = Number(patientId);
  return Number.isFinite(parsed) ? parsed : null;
}

function calculateTotalAmount(payload: Omit<Invoice, "id">) {
  return payload.lineItems.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
}

function errorResponse(message: string, error: unknown) {
  return NextResponse.json(
    {
      error: message,
      details:
        process.env.NODE_ENV === "development"
          ? error instanceof Error
            ? error.message
            : String(error)
          : undefined,
    },
    { status: 500 },
  );
}

export async function GET() {
  try {
    const result = await withOracleConnection((connection) =>
      connection.execute<InvoiceRow>(
        `
          SELECT
            ID,
            PATIENT_ID,
            TOTAL_AMOUNT,
            NOTES,
            CREATED_AT
          FROM INVOICES
          ORDER BY CREATED_AT DESC, ID DESC
        `,
        [],
        { outFormat: oracledb.OUT_FORMAT_OBJECT },
      ),
    );

    return NextResponse.json((result.rows ?? []).map(serializeInvoice));
  } catch (error) {
    console.error("GET /api/billing failed", error);
    return errorResponse("Failed to load invoices from Oracle.", error);
  }
}

export async function POST(request: Request) {
  try {
    const payload = (await request.json()) as Omit<Invoice, "id">;

    const result = await withOracleConnection((connection) =>
      connection.execute<{ ID: number }>(
        `
          INSERT INTO INVOICES (
            PATIENT_ID,
            RECORD_ID,
            TOTAL_AMOUNT,
            STATUS,
            NOTES,
            UPDATED_AT
          ) VALUES (
            :patientId,
            NULL,
            :totalAmount,
            :status,
            :notes,
            CURRENT_TIMESTAMP
          )
          RETURNING ID INTO :id
        `,
        {
          patientId: parseNumericPatientId(payload.patientId),
          totalAmount: calculateTotalAmount(payload),
          status:
            sumPayments(payload.payments) >= calculateTotalAmount(payload)
              ? "paid"
              : "pending",
          notes: buildInvoiceMetadata(payload),
          id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER },
        },
        { autoCommit: true, outFormat: oracledb.OUT_FORMAT_OBJECT },
      ),
    );

    const insertedId = (result.outBinds?.id as number[] | undefined)?.[0];

    return NextResponse.json(
      {
        id: insertedId ? String(insertedId) : "",
        ...payload,
      },
      { status: 201 },
    );
  } catch (error) {
    console.error("POST /api/billing failed", error);
    return errorResponse("Failed to save invoice to Oracle.", error);
  }
}
