import type { Db } from "mongodb";

import type {
  DentalRecord,
  Invoice,
  InvoiceLine,
  TreatmentCatalogItem,
} from "@/lib/clinic-types";
import { treatmentCatalog } from "@/lib/clinic-types";

type InvoiceDocument = Omit<Invoice, "id"> & {
  _id?: string;
};

function fallbackInvoiceNumber(record: DentalRecord) {
  const visitDate = record.visitDate.replaceAll("-", "");
  const patientSuffix = record.patientId.slice(-4).toUpperCase();
  const recordSuffix = record.id.slice(-4).toUpperCase();
  return `INV-${visitDate}-${patientSuffix}-${recordSuffix}`;
}

function groupBillableTeeth(record: DentalRecord) {
  return record.odontogram.reduce<Record<string, { toothNumbers: string[]; unitPrice: number | null }[]>>((acc, tooth) => {
    if (!tooth.billableTreatmentId) {
      return acc;
    }

    const groups = [...(acc[tooth.billableTreatmentId] ?? [])];
    const unitPrice = tooth.billableUnitPrice ?? null;
    const existingGroup = groups.find((group) => group.unitPrice === unitPrice);

    if (existingGroup) {
      existingGroup.toothNumbers.push(tooth.toothNumber);
    } else {
      groups.push({
        toothNumbers: [tooth.toothNumber],
        unitPrice,
      });
    }

    acc[tooth.billableTreatmentId] = groups;
    return acc;
  }, {});
}

function buildLineItem(
  catalogItem: TreatmentCatalogItem,
  toothNumbers: string[],
  linkedRecordId: string,
  unitPriceOverride: number | null,
): InvoiceLine {
  return {
    treatmentId: catalogItem.id,
    treatment: catalogItem.name,
    quantity: catalogItem.pricingModel === "per-case" ? 1 : toothNumbers.length,
    unitPrice: unitPriceOverride ?? catalogItem.defaultPrice,
    pricingModel: catalogItem.pricingModel,
    linkedRecordId,
    toothNumbers,
    autoGenerated: true,
  };
}

export function deriveInvoiceLineItems(record: DentalRecord): InvoiceLine[] {
  const groupedTeeth = groupBillableTeeth(record);

  return treatmentCatalog.flatMap((catalogItem) => {
    const groupedEntries = groupedTeeth[catalogItem.id] ?? [];

    if (groupedEntries.length === 0) {
      return [];
    }

    if (catalogItem.pricingModel === "per-case") {
      const mergedToothNumbers = groupedEntries.flatMap((entry) => entry.toothNumbers);
      const unitPriceOverride =
        groupedEntries.find((entry) => entry.unitPrice !== null)?.unitPrice ?? null;

      return [buildLineItem(catalogItem, mergedToothNumbers, record.id, unitPriceOverride)];
    }

    return groupedEntries.map((entry) =>
      buildLineItem(catalogItem, entry.toothNumbers, record.id, entry.unitPrice),
    );
  });
}

export async function upsertAutoInvoiceForRecord(db: Db, record: DentalRecord) {
  const lineItems = deriveInvoiceLineItems(record);
  const invoices = db.collection<InvoiceDocument>("billing_invoices");
  const existingInvoice = await invoices.findOne({ linkedRecordId: record.id });

  if (lineItems.length === 0 && !existingInvoice) {
    return null;
  }

  const nextInvoice: Omit<Invoice, "id"> = {
    patientId: record.patientId,
    patientName: record.patientName,
    invoiceNumber: existingInvoice?.invoiceNumber ?? fallbackInvoiceNumber(record),
    issueDate: record.visitDate,
    linkedRecordId: record.id,
    autoGenerated: true,
    lineItems,
    payments: existingInvoice?.payments ?? [],
    notes: existingInvoice?.notes ?? "",
  };

  if (existingInvoice) {
    await invoices.updateOne(
      { _id: existingInvoice._id },
      {
        $set: {
          patientId: nextInvoice.patientId,
          patientName: nextInvoice.patientName,
          invoiceNumber: nextInvoice.invoiceNumber,
          issueDate: nextInvoice.issueDate,
          linkedRecordId: nextInvoice.linkedRecordId,
          autoGenerated: nextInvoice.autoGenerated,
          lineItems: nextInvoice.lineItems,
          notes: nextInvoice.notes,
        },
      },
    );

    return {
      id: String(existingInvoice._id),
      ...nextInvoice,
    } satisfies Invoice;
  }

  const result = await invoices.insertOne(nextInvoice);

  return {
    id: String(result.insertedId),
    ...nextInvoice,
  } satisfies Invoice;
}
