import type { Db } from "mongodb";

import type {
  DentalRecord,
  Invoice,
  InvoiceLine,
  TreatmentCatalogItem,
} from "@/lib/clinic-types";
import { treatmentCatalog } from "@/lib/clinic-types";

type InvoiceDocument = Omit<Invoice, "id"> & {
  _id?: string;
};

function fallbackInvoiceNumber(record: DentalRecord) {
  const visitDate = record.visitDate.replaceAll("-", "");
  const patientSuffix = record.patientId.slice(-4).toUpperCase();
  const recordSuffix = record.id.slice(-4).toUpperCase();
  return `INV-${visitDate}-${patientSuffix}-${recordSuffix}`;
}

function groupBillableTeeth(record: DentalRecord) {
  return record.odontogram.reduce<Record<string, string[]>>((acc, tooth) => {
    if (!tooth.billableTreatmentId) {
      return acc;
    }

    acc[tooth.billableTreatmentId] = [
      ...(acc[tooth.billableTreatmentId] ?? []),
      tooth.toothNumber,
    ];
    return acc;
  }, {});
}

function buildLineItem(
  catalogItem: TreatmentCatalogItem,
  toothNumbers: string[],
  linkedRecordId: string,
): InvoiceLine {
  return {
    treatmentId: catalogItem.id,
    treatment: catalogItem.name,
    quantity: catalogItem.pricingModel === "per-case" ? 1 : toothNumbers.length,
    unitPrice: catalogItem.defaultPrice,
    pricingModel: catalogItem.pricingModel,
    linkedRecordId,
    toothNumbers,
    autoGenerated: true,
  };
}

export function deriveInvoiceLineItems(record: DentalRecord): InvoiceLine[] {
  const groupedTeeth = groupBillableTeeth(record);

  return treatmentCatalog.flatMap((catalogItem) => {
    const toothNumbers = groupedTeeth[catalogItem.id] ?? [];

    if (toothNumbers.length === 0) {
      return [];
    }

    return [buildLineItem(catalogItem, toothNumbers, record.id)];
  });
}

export async function upsertAutoInvoiceForRecord(db: Db, record: DentalRecord) {
  const lineItems = deriveInvoiceLineItems(record);
  const invoices = db.collection<InvoiceDocument>("billing_invoices");
  const existingInvoice = await invoices.findOne({ linkedRecordId: record.id });

  if (lineItems.length === 0 && !existingInvoice) {
    return null;
  }

  const nextInvoice: Omit<Invoice, "id"> = {
    patientId: record.patientId,
    patientName: record.patientName,
    invoiceNumber: existingInvoice?.invoiceNumber ?? fallbackInvoiceNumber(record),
    issueDate: record.visitDate,
    linkedRecordId: record.id,
    autoGenerated: true,
    lineItems,
    payments: existingInvoice?.payments ?? [],
    notes: existingInvoice?.notes ?? "",
  };

  if (existingInvoice) {
    await invoices.updateOne(
      { _id: existingInvoice._id },
      {
        $set: {
          patientId: nextInvoice.patientId,
          patientName: nextInvoice.patientName,
          invoiceNumber: nextInvoice.invoiceNumber,
          issueDate: nextInvoice.issueDate,
          linkedRecordId: nextInvoice.linkedRecordId,
          autoGenerated: nextInvoice.autoGenerated,
          lineItems: nextInvoice.lineItems,
          notes: nextInvoice.notes,
        },
      },
    );

    return {
      id: String(existingInvoice._id),
      ...nextInvoice,
    } satisfies Invoice;
  }

  const result = await invoices.insertOne(nextInvoice);

  return {
    id: String(result.insertedId),
    ...nextInvoice,
  } satisfies Invoice;
}
