import type { Db } from "mongodb";

import type {
  DentalRecord,
  Invoice,
  InvoiceLine,
  ToothCondition,
  ToothConditionPricingItem,
} from "@/lib/clinic-types";
import { toothConditionOptions, toothConditionPricing } from "@/lib/clinic-types";

type InvoiceDocument = Omit<Invoice, "id"> & {
  _id?: string;
};

function fallbackInvoiceNumber(record: DentalRecord) {
  const visitDate = record.visitDate.replaceAll("-", "");
  const patientSuffix = record.patientId.slice(-4).toUpperCase();
  const recordSuffix = record.id.slice(-4).toUpperCase();
  return `INV-${visitDate}-${patientSuffix}-${recordSuffix}`;
}

function groupBillableTeeth(record: DentalRecord) {
  return record.odontogram.reduce<
    Record<ToothCondition, { toothNumbers: string[]; unitPrice: number }[]>
  >((acc, tooth) => {
    const pricingRule = toothConditionPricing[tooth.condition];
    const unitPrice = tooth.conditionPrice ?? pricingRule.defaultPrice;

    if (unitPrice === null) {
      return acc;
    }

    const groups = [...(acc[tooth.condition] ?? [])];
    const existingGroup = groups.find((group) => group.unitPrice === unitPrice);

    if (existingGroup) {
      existingGroup.toothNumbers.push(tooth.toothNumber);
    } else {
      groups.push({
        toothNumbers: [tooth.toothNumber],
        unitPrice,
      });
    }

    acc[tooth.condition] = groups;
    return acc;
  }, {} as Record<ToothCondition, { toothNumbers: string[]; unitPrice: number }[]>);
}

function buildLineItem(
  pricingRule: ToothConditionPricingItem,
  toothNumbers: string[],
  linkedRecordId: string,
  unitPrice: number,
): InvoiceLine {
  return {
    treatmentId: pricingRule.treatmentId,
    treatment: pricingRule.treatment,
    quantity: pricingRule.pricingModel === "per-case" ? 1 : toothNumbers.length,
    unitPrice,
    pricingModel: pricingRule.pricingModel,
    linkedRecordId,
    toothNumbers,
    autoGenerated: true,
  };
}

export function deriveInvoiceLineItems(record: DentalRecord): InvoiceLine[] {
  const groupedTeeth = groupBillableTeeth(record);

  return toothConditionOptions.flatMap((condition) => {
    const pricingRule = toothConditionPricing[condition];
    const groupedEntries = groupedTeeth[condition] ?? [];

    if (groupedEntries.length === 0) {
      return [];
    }

    if (pricingRule.pricingModel === "per-case") {
      const mergedToothNumbers = groupedEntries.flatMap((entry) => entry.toothNumbers);
      const unitPrice = groupedEntries[0]?.unitPrice ?? pricingRule.defaultPrice;

      if (unitPrice === null) {
        return [];
      }

      return [buildLineItem(pricingRule, mergedToothNumbers, record.id, unitPrice)];
    }

    return groupedEntries.map((entry) =>
      buildLineItem(pricingRule, entry.toothNumbers, record.id, entry.unitPrice),
    );
  });
}

export async function upsertAutoInvoiceForRecord(db: Db, record: DentalRecord) {
  const lineItems = deriveInvoiceLineItems(record);
  const invoices = db.collection<InvoiceDocument>("billing_invoices");
  const existingInvoice = await invoices.findOne({ linkedRecordId: record.id });

  if (lineItems.length === 0 && !existingInvoice) {
    return null;
  }

  const nextInvoice: Omit<Invoice, "id"> = {
    patientId: record.patientId,
    patientName: record.patientName,
    invoiceNumber: existingInvoice?.invoiceNumber ?? fallbackInvoiceNumber(record),
    issueDate: record.visitDate,
    linkedRecordId: record.id,
    autoGenerated: true,
    lineItems,
    payments: existingInvoice?.payments ?? [],
    notes: existingInvoice?.notes ?? "",
  };

  if (existingInvoice) {
    await invoices.updateOne(
      { _id: existingInvoice._id },
      {
        $set: {
          patientId: nextInvoice.patientId,
          patientName: nextInvoice.patientName,
          invoiceNumber: nextInvoice.invoiceNumber,
          issueDate: nextInvoice.issueDate,
          linkedRecordId: nextInvoice.linkedRecordId,
          autoGenerated: nextInvoice.autoGenerated,
          lineItems: nextInvoice.lineItems,
          notes: nextInvoice.notes,
        },
      },
    );

    return {
      id: String(existingInvoice._id),
      ...nextInvoice,
    } satisfies Invoice;
  }

  const result = await invoices.insertOne(nextInvoice);

  return {
    id: String(result.insertedId),
    ...nextInvoice,
  } satisfies Invoice;
}
