"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";

import { AdminShell } from "@/components/admin-shell";
import {
  initialPaymentForm,
  paymentMethodOptions,
  type Invoice,
  type PatientProfile,
  type PaymentFormState,
} from "@/lib/clinic-types";

function currency(amount: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
  }).format(amount);
}

function formatDateLabel(date: string) {
  if (!date) {
    return "Not set";
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(date));
}

function invoiceTotal(invoice: Invoice) {
  return invoice.lineItems.reduce(
    (sum, item) => sum + item.quantity * item.unitPrice,
    0,
  );
}

function invoicePaid(invoice: Invoice) {
  return invoice.payments.reduce((sum, payment) => sum + payment.amount, 0);
}

export default function BillingPage() {
  const [patients, setPatients] = useState<PatientProfile[]>([]);
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [selectedPatientId, setSelectedPatientId] = useState("");
  const [selectedInvoiceId, setSelectedInvoiceId] = useState("");
  const [paymentForm, setPaymentForm] = useState<PaymentFormState>(initialPaymentForm);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  useEffect(() => {
    async function loadBillingData() {
      try {
        setIsLoading(true);
        setErrorMessage("");

        const [patientsResponse, invoicesResponse] = await Promise.all([
          fetch("/api/patients", { cache: "no-store" }),
          fetch("/api/billing", { cache: "no-store" }),
        ]);

        if (!patientsResponse.ok || !invoicesResponse.ok) {
          throw new Error(
            `${patientsResponse.ok ? "" : await patientsResponse.text()} ${
              invoicesResponse.ok ? "" : await invoicesResponse.text()
            }`.trim(),
          );
        }

        const [patientsData, invoicesData] = await Promise.all([
          (await patientsResponse.json()) as PatientProfile[],
          (await invoicesResponse.json()) as Invoice[],
        ]);

        setPatients(patientsData);
        setInvoices(invoicesData);
        setSelectedInvoiceId(invoicesData[0]?.id ?? "");
      } catch (error) {
        console.error(error);
        setErrorMessage(
          error instanceof Error ? error.message : "Unable to load billing data.",
        );
      } finally {
        setIsLoading(false);
      }
    }

    loadBillingData();
  }, []);

  function handlePaymentFieldChange(
    event: ChangeEvent<HTMLInputElement | HTMLSelectElement>,
  ) {
    const { name, value } = event.target;
    setPaymentForm((current) => ({
      ...current,
      [name]: name === "amount" ? Number(value) : value,
    }));
  }

  const visibleInvoices = invoices.filter((invoice) =>
    selectedPatientId ? invoice.patientId === selectedPatientId : true,
  );

  const selectedInvoice =
    visibleInvoices.find((invoice) => invoice.id === selectedInvoiceId) ??
    visibleInvoices[0] ??
    null;

  async function handlePaymentSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (!selectedInvoice || paymentForm.amount <= 0 || !paymentForm.paidAt) {
      return;
    }

    try {
      setIsSaving(true);
      setErrorMessage("");

      const response = await fetch(`/api/billing/${selectedInvoice.id}`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          appendPayment: paymentForm,
        }),
      });

      if (!response.ok) {
        throw new Error(await response.text());
      }

      setInvoices((current) =>
        current.map((invoice) =>
          invoice.id === selectedInvoice.id
            ? { ...invoice, payments: [...invoice.payments, paymentForm] }
            : invoice,
        ),
      );
      setPaymentForm(initialPaymentForm);
    } catch (error) {
      console.error(error);
      setErrorMessage(
        error instanceof Error ? error.message : "Payment could not be recorded.",
      );
    } finally {
      setIsSaving(false);
    }
  }

  const totalRevenue = invoices.reduce((sum, invoice) => sum + invoicePaid(invoice), 0);
  const totalOutstanding = invoices.reduce(
    (sum, invoice) => sum + Math.max(invoiceTotal(invoice) - invoicePaid(invoice), 0),
    0,
  );
  const autoGeneratedInvoices = invoices.filter((invoice) => invoice.autoGenerated);
  const selectedInvoiceTotal = selectedInvoice ? invoiceTotal(selectedInvoice) : 0;
  const selectedInvoicePaid = selectedInvoice ? invoicePaid(selectedInvoice) : 0;
  const selectedInvoiceOutstanding = Math.max(
    selectedInvoiceTotal - selectedInvoicePaid,
    0,
  );

  return (
    <AdminShell>
      <div className="w-full space-y-6">
        <header className="rounded-[28px] border border-white/80 bg-white/80 p-6 shadow-[0_20px_50px_rgba(15,23,42,0.08)]">
          <p className="text-xs font-semibold uppercase tracking-[0.35em] text-sky-700">
            Module D
          </p>
          <div className="mt-3 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <h2 className="text-3xl font-semibold tracking-tight text-slate-950">
                Billing & Payments
              </h2>
              <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">
                Invoice charges are now generated automatically from billable
                treatments selected in EMR. Staff only need to review charges and
                record the payment received.
              </p>
            </div>
            <div className="grid grid-cols-3 gap-3">
              <div className="rounded-2xl bg-slate-950 px-4 py-3 text-white">
                <p className="text-xs uppercase tracking-[0.22em] text-cyan-200">
                  Invoices
                </p>
                <p className="mt-2 text-2xl font-semibold">{invoices.length}</p>
              </div>
              <div className="rounded-2xl bg-sky-50 px-4 py-3 ring-1 ring-sky-100">
                <p className="text-xs uppercase tracking-[0.22em] text-slate-500">
                  Revenue
                </p>
                <p className="mt-2 text-2xl font-semibold text-slate-900">
                  {currency(totalRevenue)}
                </p>
              </div>
              <div className="rounded-2xl bg-sky-50 px-4 py-3 ring-1 ring-sky-100">
                <p className="text-xs uppercase tracking-[0.22em] text-slate-500">
                  Outstanding
                </p>
                <p className="mt-2 text-2xl font-semibold text-slate-900">
                  {currency(totalOutstanding)}
                </p>
              </div>
            </div>
          </div>
        </header>

        {isLoading ? (
          <div className="rounded-[24px] border border-sky-100 bg-sky-50 px-5 py-4 text-sm text-sky-800">
            Loading billing data from MongoDB...
          </div>
        ) : null}

        {errorMessage ? (
          <div className="rounded-[24px] border border-rose-100 bg-rose-50 px-5 py-4 text-sm text-rose-700">
            {errorMessage}
          </div>
        ) : null}

        <div className="grid gap-6 xl:grid-cols-[380px_minmax(0,1fr)]">
          <section className="rounded-[28px] border border-white/80 bg-white/85 p-6 shadow-[0_20px_50px_rgba(15,23,42,0.08)]">
            <div className="space-y-4">
              <div>
                <h3 className="text-xl font-semibold text-slate-950">Auto-Generated Invoices</h3>
                <p className="mt-1 text-sm text-slate-500">
                  Each invoice is linked to an EMR visit and updates when that record changes.
                </p>
              </div>

              <label className="space-y-1">
                <span className="text-sm font-medium text-slate-700">Filter by Patient</span>
                <select
                  value={selectedPatientId}
                  onChange={(event) => {
                    setSelectedPatientId(event.target.value);
                    setSelectedInvoiceId("");
                  }}
                  className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none transition focus:border-sky-400 focus:bg-white"
                >
                  <option value="">All patients</option>
                  {patients.map((patient) => (
                    <option key={patient.id} value={patient.id}>
                      {patient.fullName}
                    </option>
                  ))}
                </select>
              </label>
            </div>

            <div className="mt-5 space-y-3">
              {visibleInvoices.length === 0 ? (
                <p className="rounded-2xl bg-slate-100 p-4 text-sm text-slate-600">
                  No invoices found. Save a billable EMR record first to generate one automatically.
                </p>
              ) : (
                visibleInvoices.map((invoice) => {
                  const total = invoiceTotal(invoice);
                  const paid = invoicePaid(invoice);
                  const outstanding = Math.max(total - paid, 0);
                  const isActive = invoice.id === (selectedInvoice?.id ?? "");

                  return (
                    <button
                      key={invoice.id}
                      type="button"
                      onClick={() => setSelectedInvoiceId(invoice.id)}
                      className={`w-full rounded-3xl border p-4 text-left transition ${
                        isActive
                          ? "border-sky-300 bg-sky-50 shadow-[0_12px_28px_rgba(14,165,233,0.10)]"
                          : "border-slate-200 bg-slate-50 hover:bg-white"
                      }`}
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <p className="font-semibold text-slate-900">{invoice.invoiceNumber}</p>
                          <p className="mt-1 text-sm text-slate-500">
                            {invoice.patientName} | {formatDateLabel(invoice.issueDate)}
                          </p>
                        </div>
                        <span className="rounded-full bg-white px-3 py-1 text-xs font-medium text-slate-600 ring-1 ring-slate-200">
                          {outstanding === 0 ? "Paid" : "Outstanding"}
                        </span>
                      </div>
                      <div className="mt-4 grid grid-cols-3 gap-2 text-xs">
                        <div className="rounded-2xl bg-white p-3 ring-1 ring-slate-200">
                          <p className="text-slate-500">Total</p>
                          <p className="mt-1 font-semibold text-slate-900">{currency(total)}</p>
                        </div>
                        <div className="rounded-2xl bg-white p-3 ring-1 ring-slate-200">
                          <p className="text-slate-500">Paid</p>
                          <p className="mt-1 font-semibold text-emerald-700">{currency(paid)}</p>
                        </div>
                        <div className="rounded-2xl bg-white p-3 ring-1 ring-slate-200">
                          <p className="text-slate-500">Balance</p>
                          <p className="mt-1 font-semibold text-rose-700">
                            {currency(outstanding)}
                          </p>
                        </div>
                      </div>
                    </button>
                  );
                })
              )}
            </div>
          </section>

          <div className="space-y-6">
            <section className="rounded-[28px] border border-white/80 bg-white/85 p-6 shadow-[0_20px_50px_rgba(15,23,42,0.08)]">
              <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between">
                <div>
                  <h3 className="text-xl font-semibold text-slate-950">Invoice Detail</h3>
                  <p className="mt-1 text-sm text-slate-500">
                    Charges come from the treatment catalog and billable tooth entries in EMR.
                  </p>
                </div>
                <span className="rounded-full bg-sky-100 px-3 py-1 text-xs font-semibold text-sky-700">
                  {autoGeneratedInvoices.length} auto-generated
                </span>
              </div>

              {!selectedInvoice ? (
                <p className="mt-4 rounded-2xl bg-slate-100 p-4 text-sm text-slate-600">
                  Select an invoice to review charges and record payment.
                </p>
              ) : (
                <div className="mt-5 space-y-5">
                  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
                    <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-100">
                      <p className="text-sm text-slate-500">Patient</p>
                      <p className="mt-1 font-semibold text-slate-950">
                        {selectedInvoice.patientName}
                      </p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-100">
                      <p className="text-sm text-slate-500">Visit Date</p>
                      <p className="mt-1 font-semibold text-slate-950">
                        {formatDateLabel(selectedInvoice.issueDate)}
                      </p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-100">
                      <p className="text-sm text-slate-500">Linked EMR</p>
                      <p className="mt-1 font-semibold text-slate-950">
                        {selectedInvoice.linkedRecordId || "Not linked"}
                      </p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-100">
                      <p className="text-sm text-slate-500">Invoice Type</p>
                      <p className="mt-1 font-semibold text-slate-950">
                        {selectedInvoice.autoGenerated ? "Auto-generated" : "Manual"}
                      </p>
                    </div>
                  </div>

                  <div className="rounded-3xl bg-slate-50 p-4">
                    <h4 className="text-base font-semibold text-slate-950">Treatment Charges</h4>
                    <div className="mt-4 space-y-3">
                      {selectedInvoice.lineItems.length === 0 ? (
                        <p className="rounded-2xl bg-white p-4 text-sm text-slate-600 ring-1 ring-slate-200">
                          No billable treatments have been selected for this visit yet.
                        </p>
                      ) : (
                        selectedInvoice.lineItems.map((item, index) => (
                          <article
                            key={`${item.treatmentId}-${index}`}
                            className="rounded-2xl bg-white p-4 ring-1 ring-slate-200"
                          >
                            <div className="flex items-start justify-between gap-3">
                              <div>
                                <p className="font-medium text-slate-900">{item.treatment}</p>
                                <p className="mt-1 text-sm text-slate-500">
                                  {item.quantity} x {currency(item.unitPrice)} | {item.pricingModel}
                                </p>
                                <p className="mt-2 text-xs uppercase tracking-[0.18em] text-slate-500">
                                  Teeth:{" "}
                                  {item.toothNumbers.length > 0
                                    ? item.toothNumbers.join(", ")
                                    : "Case level"}
                                </p>
                              </div>
                              <span className="font-semibold text-slate-900">
                                {currency(item.quantity * item.unitPrice)}
                              </span>
                            </div>
                          </article>
                        ))
                      )}
                    </div>
                  </div>

                  <div className="grid gap-3 md:grid-cols-3">
                    <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-100">
                      <p className="text-sm text-slate-500">Invoice Total</p>
                      <p className="mt-1 text-2xl font-semibold text-slate-950">
                        {currency(selectedInvoiceTotal)}
                      </p>
                    </div>
                    <div className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-100">
                      <p className="text-sm text-slate-500">Paid</p>
                      <p className="mt-1 text-2xl font-semibold text-emerald-700">
                        {currency(selectedInvoicePaid)}
                      </p>
                    </div>
                    <div className="rounded-2xl bg-slate-950 p-4 text-white">
                      <p className="text-sm text-slate-300">Outstanding Balance</p>
                      <p className="mt-1 text-2xl font-semibold">
                        {currency(selectedInvoiceOutstanding)}
                      </p>
                    </div>
                  </div>
                </div>
              )}
            </section>

            <section className="rounded-[28px] border border-white/80 bg-white/85 p-6 shadow-[0_20px_50px_rgba(15,23,42,0.08)]">
              <div>
                <h3 className="text-xl font-semibold text-slate-950">Record Payment</h3>
                <p className="mt-1 text-sm text-slate-500">
                  Payment remains manual even though invoice charges are automatic.
                </p>
              </div>

              {!selectedInvoice ? (
                <p className="mt-4 rounded-2xl bg-slate-100 p-4 text-sm text-slate-600">
                  Select an invoice first.
                </p>
              ) : (
                <form className="mt-6 space-y-6" onSubmit={handlePaymentSubmit}>
                  <div className="grid gap-4 md:grid-cols-4">
                    <label className="space-y-1">
                      <span className="text-sm font-medium text-slate-700">Amount</span>
                      <input
                        type="number"
                        min="0"
                        name="amount"
                        value={paymentForm.amount}
                        onChange={handlePaymentFieldChange}
                        placeholder={selectedInvoiceOutstanding.toString()}
                        className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none transition focus:border-sky-400 focus:bg-white"
                      />
                    </label>
                    <label className="space-y-1">
                      <span className="text-sm font-medium text-slate-700">Method</span>
                      <select
                        name="method"
                        value={paymentForm.method}
                        onChange={handlePaymentFieldChange}
                        className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none transition focus:border-sky-400 focus:bg-white"
                      >
                        {paymentMethodOptions.map((method) => (
                          <option key={method} value={method}>
                            {method}
                          </option>
                        ))}
                      </select>
                    </label>
                    <label className="space-y-1">
                      <span className="text-sm font-medium text-slate-700">Paid At</span>
                      <input
                        type="date"
                        name="paidAt"
                        value={paymentForm.paidAt}
                        onChange={handlePaymentFieldChange}
                        className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none transition focus:border-sky-400 focus:bg-white"
                      />
                    </label>
                    <label className="space-y-1">
                      <span className="text-sm font-medium text-slate-700">Reference</span>
                      <input
                        name="reference"
                        value={paymentForm.reference}
                        onChange={handlePaymentFieldChange}
                        placeholder="Receipt / txn ref"
                        className="w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 outline-none transition focus:border-sky-400 focus:bg-white"
                      />
                    </label>
                  </div>

                  <button
                    type="submit"
                    disabled={isSaving || selectedInvoiceOutstanding === 0}
                    className="rounded-2xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:bg-slate-300"
                  >
                    {isSaving ? "Recording Payment..." : "Record Payment"}
                  </button>
                </form>
              )}
            </section>

            <section className="rounded-[28px] border border-white/80 bg-slate-950 p-6 text-white shadow-[0_20px_50px_rgba(15,23,42,0.16)]">
              <p className="text-xs uppercase tracking-[0.28em] text-cyan-200/75">
                Payment History
              </p>
              <h3 className="mt-2 text-xl font-semibold">Recorded Transactions</h3>
              <div className="mt-4 space-y-3">
                {!selectedInvoice || selectedInvoice.payments.length === 0 ? (
                  <p className="rounded-2xl bg-white/10 p-4 text-sm text-slate-300">
                    No payments recorded for the selected invoice.
                  </p>
                ) : (
                  selectedInvoice.payments.map((payment, index) => (
                    <article
                      key={`${payment.method}-${payment.paidAt}-${index}`}
                      className="rounded-2xl border border-white/10 bg-white/6 p-4"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div>
                          <p className="font-medium text-white">{currency(payment.amount)}</p>
                          <p className="mt-1 text-sm text-slate-300">
                            {payment.method} | {formatDateLabel(payment.paidAt)}
                          </p>
                        </div>
                        <span className="text-sm text-slate-300">
                          {payment.reference || "No reference"}
                        </span>
                      </div>
                    </article>
                  ))
                )}
              </div>
            </section>
          </div>
        </div>
      </div>
    </AdminShell>
  );
}
