import { NextResponse } from "next/server";

import { serializeAppointment, type AppointmentDocument } from "@/lib/appointments";
import type { Appointment, DentalRecord, Invoice, PatientProfile, StaffMember } from "@/lib/clinic-types";
import { getDatabase } from "@/lib/mongodb";
import {
  buildPatientAnalytics,
  buildPatientDuplicateCandidates,
  serializePatient,
  type PatientDocument,
} from "@/lib/patients";

type InvoiceDocument = Omit<Invoice, "id"> & {
  _id?: unknown;
};

type DentalRecordDocument = Omit<DentalRecord, "id"> & {
  _id?: unknown;
};

type StaffDocument = Omit<StaffMember, "id"> & {
  _id?: unknown;
};

type OdontogramToothDocument = DentalRecordDocument["odontogram"][number] & {
  billableUnitPrice?: number | null;
};

function normalizeOdontogram(odontogram: OdontogramToothDocument[] = []) {
  return odontogram.map((tooth) => ({
    toothNumber: tooth.toothNumber,
    condition: tooth.condition,
    notes: tooth.notes ?? "",
    treatmentProcess: tooth.treatmentProcess ?? "",
    treatmentStatus: tooth.treatmentStatus ?? "planned",
    conditionPrice: tooth.conditionPrice ?? tooth.billableUnitPrice ?? null,
  }));
}

function serializeInvoice(invoice: InvoiceDocument): Invoice {
  return {
    id: String(invoice._id),
    patientId: invoice.patientId,
    patientName: invoice.patientName,
    invoiceNumber: invoice.invoiceNumber,
    issueDate: invoice.issueDate,
    linkedRecordId: invoice.linkedRecordId ?? "",
    autoGenerated: invoice.autoGenerated ?? false,
    lineItems: (invoice.lineItems ?? []).map((item) => ({
      treatmentId: item.treatmentId ?? "",
      treatment: item.treatment,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      pricingModel: item.pricingModel ?? "per-tooth",
      linkedRecordId: item.linkedRecordId ?? invoice.linkedRecordId ?? "",
      toothNumbers: item.toothNumbers ?? [],
      autoGenerated: item.autoGenerated ?? false,
    })),
    payments: invoice.payments ?? [],
    notes: invoice.notes ?? "",
  };
}

function serializeDentalRecord(record: DentalRecordDocument): DentalRecord {
  return {
    id: String(record._id),
    patientId: record.patientId,
    patientName: record.patientName,
    visitDate: record.visitDate,
    chiefComplaint: record.chiefComplaint,
    consultationNotes: record.consultationNotes,
    diagnoses: record.diagnoses,
    treatmentPlan: record.treatmentPlan,
    treatmentStep: record.treatmentStep ?? "",
    treatmentStatus: record.treatmentStatus ?? "planned",
    procedureHistory: record.procedureHistory,
    clinicalAttachments: record.clinicalAttachments ?? [],
    odontogram: normalizeOdontogram(record.odontogram as OdontogramToothDocument[]),
  };
}

function serializeStaff(member: StaffDocument): StaffMember {
  return {
    id: String(member._id),
    fullName: member.fullName,
    role: member.role,
    email: member.email,
    phone: member.phone,
    permissions: member.permissions ?? [],
    skills: member.skills ?? [],
    schedule: member.schedule ?? [],
    availabilityStatus: member.availabilityStatus,
  };
}

function errorResponse(message: string, error: unknown) {
  return NextResponse.json(
    {
      error: message,
      details:
        process.env.NODE_ENV === "development"
          ? error instanceof Error
            ? error.message
            : String(error)
          : undefined,
    },
    { status: 500 },
  );
}

export async function GET() {
  try {
    const db = await getDatabase();
    const [patients, appointments, invoices, records, staffMembers] = await Promise.all([
      db.collection<PatientDocument>("patients").find({}).sort({ _id: -1 }).toArray(),
      db
        .collection<AppointmentDocument>("appointments")
        .find({})
        .sort({ date: 1, startTime: 1, time: 1, _id: -1 })
        .toArray(),
      db
        .collection<InvoiceDocument>("billing_invoices")
        .find({})
        .sort({ issueDate: -1, _id: -1 })
        .toArray(),
      db
        .collection<DentalRecordDocument>("emr_records")
        .find({})
        .sort({ visitDate: -1, _id: -1 })
        .toArray(),
      db.collection<StaffDocument>("staff").find({}).sort({ role: 1, fullName: 1 }).toArray(),
    ]);

    const serializedAppointments = appointments.map((appointment) =>
      serializeAppointment(appointment),
    );
    const serializedInvoices = invoices.map((invoice) => serializeInvoice(invoice));
    const serializedRecords = records.map((record) => serializeDentalRecord(record));
    const serializedStaff = staffMembers.map((member) => serializeStaff(member));
    const serializedPatients = patients.map((patient) =>
      serializePatient(patient, {
        analytics: buildPatientAnalytics(
          String(patient._id),
          serializedAppointments,
          serializedInvoices,
          serializedRecords,
        ),
        appointments: serializedAppointments.filter(
          (appointment) => appointment.patientId === String(patient._id),
        ),
        invoices: serializedInvoices.filter((invoice) => invoice.patientId === String(patient._id)),
      }),
    );

    return NextResponse.json({
      patients: serializedPatients.map((patient) => ({
        ...patient,
        duplicateCandidates: buildPatientDuplicateCandidates(patient, serializedPatients),
      })) satisfies PatientProfile[],
      appointments: serializedAppointments satisfies Appointment[],
      invoices: serializedInvoices satisfies Invoice[],
      records: serializedRecords satisfies DentalRecord[],
      staffMembers: serializedStaff satisfies StaffMember[],
    });
  } catch (error) {
    console.error("GET /api/overview failed", error);
    return errorResponse("Failed to load overview data.", error);
  }
}
